#!/usr/bin/env ruby

# generates a Markdown table of the defect bits and their descriptions

require 'json'

unless ENV.has_key? 'QADB'
  $stderr.puts 'you need to source environment variables'
  exit 1
end

puts """<!-- THE TABLE BELOW WAS GENERATED BY #{$0} -->
<table>
  <colgroup>
    <col style=\"width: 5%\">
    <col style=\"width: 25%\">
    <col style=\"width: 35%\">
    <col style=\"width: 35%\">
  </colgroup>
  <thead>
    <tr>
      <th>Bit</th>
      <th>Name</th>
      <th>Description</th>
      <th>Additional Notes</th>
    </tr>
  </thead>
  <tbody>"""

def puts_row(columns)
  columns_html = columns
    .map{ |it| "<td>#{it}</td>" }
    .map{ |it| it.gsub(/`([^`]+)`/, '<code>\1</code>') }
    .map{ |it| it.gsub(/__([^`]+)__/, '<strong>\1</strong>') }
    .map{ |it| it.gsub(/_([^`]+)_/, '<em>\1</em>') }
  puts "    <tr>"
  puts "      " + columns_html.join("\n      ")
  puts "    </tr>"
end

bits_with_footnotes = {
  'SectorLoss' => 1,
  'LossFT' => 1,
}
footnotes = {
  1 => 'this bit may not be reliably defined in later datasets; use the other outlier bits instead'
}

File.open("#{ENV['QADB']}/qadb/defect_definitions.json") do |defect_file|
  defect_defs = JSON.load defect_file
  defect_defs.each do |defect_def|
    defect_cols = ['bit_number', 'bit_name', 'description', 'documentation'].map do |k|
      if k == 'bit_name'
        subscript = bits_with_footnotes.has_key?(defect_def[k]) ? "<sup>#{bits_with_footnotes[defect_def[k]]}</sup>" : ''
        "`#{defect_def[k]}`#{subscript}"
      else
        defect_def[k].to_s
      end
    end
    puts_row defect_cols
  end
end

puts """  </tbody>
</table>
"""

puts ''
footnotes.each do |num, footnote|
  puts "> #{num}. #{footnote}"
end

puts "<!-- THE TABLE ABOVE WAS GENERATED BY #{$0} -->"
