name: ci

on:
  pull_request:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:

# check consistency between Groovy and C++ APIs
  groovy_vs_cpp:
    runs-on: [ ubuntu-latest ]
    strategy:
      fail-fast: false
      matrix:
        dataset: [ rga_inbending, rga_outbending, rga_spring19, rgb_fall, rgb_spring, rgb_winter, rgk_6, rgk_7 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup_groovy
        run: |
          sudo apt install groovy
      - name: env
        run: |
          source env.sh
          echo "QADB=${QADB}" >> $GITHUB_ENV
          echo "JYPATH=${JYPATH}" >> $GITHUB_ENV
      - name: compile_cpp_tests
        run: |
          cd srcC/tests
          make
      - name: test_diff_groovy_cpp
        run: |
          tests/test_diffGroovyCpp.loop.sh ${{matrix.dataset}}
      - name: collect_artifacts
        run: |
          mkdir -p groovy_vs_cpp/${{matrix.dataset}}
          mv tmp/* groovy_vs_cpp/${{matrix.dataset}}
      - name: upload_artifacts
        uses: actions/upload-artifact@v2
        with:
          name: groovy_vs_cpp--${{matrix.dataset}}
          retention-days: 1
          path: groovy_vs_cpp

# collect artifacts
  collect:
    if: ${{always()}}
    needs: 
      - groovy_vs_cpp
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: tree-artifacts
        run: tree artifacts
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          retention-days: 14
          name: _artifacts
          path: artifacts
